blog/urls.py
from django.urls import path
from . import views

app_name = 'blog'

urlpatterns = [
    path('', views.all_blogs, name='all_blogs'),
    path('<int:blog_id>/', views.detail, name='detail'),
]

khram_nikity_ispovednika/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from portfolio import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.home, name='home'),
    path('blog/', include('blog.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models

class Blog(models.Model):
    title = models.CharField(max_length=200)
    description = models.TextField()
    date = models.DateField()

    def __str__(self):
        return self.title

portfolio/models.py
from django.db import models

class Project(models.Model):
    title = models.CharField(max_length=100)
    description = models.CharField(max_length=250)
    image = models.ImageField(upload_to='portfolio/images/', blank=True)
    url = models.URLField(blank=True)

    def __str__(self):
        return self.title

blog/views.py
from django.shortcuts import render, get_object_or_404
from .models import Blog

def all_blogs(request):
    blogs = Blog.objects.order_by('-date')[:5]
    return render(request, 'blog/all_blogs.html', {'blogs':blogs})

def detail(request, blog_id):
    blog = get_object_or_404(Blog, pk=blog_id)
    return render(request, 'blog/detail.html', {'blog':blog})

portfolio/views.py
from django.shortcuts import render
from .models import Project

def home(request):
    projects = Project.objects.all()
    return render(request, 'portfolio/home.html', {'projects':projects})

blog/templates/blog/all_blogs.html
{% extends 'portfolio/base.html' %}
{% block content %}
<h1 class="about_title">Расписание Службы</h1>
<section class="timetable">
    <div class="container">
        {% for blog in blogs %}
        <h1 class="timetable_text">Расписание на {{ blog.date }}</h1>
            <div class="timetable_wrapper">
                <a href="{% url 'blog:detail' blog.id %}"><h2>{{ blog.title }}</h2></a>
                <p>{{ blog.description }}</p>
                {% endfor %}
            </div>
    </div>
</section>
{% endblock %}

blog/templates/blog/detail.html
{% extends 'portfolio/base.html' %}
{% block content %}

<section class="timetable">
    <div class="container">
        <h1 class="timetable_text">Расписание на {{ blog.date }}</h1>
        <br>
        <div class="timetable_wrapper">
            <h2>{{ blog.title }}</h2>
            <br>
            <p class="timetable_descr">{{ blog.description }}</p>
        </div>
    </div>
</section>
{% endblock %}

portfolio/templates/portfolio/base.html
{% load static %}

<!doctype html>
<html lang="ru">
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Храм Никиты Исповедника</title>
    <link rel="shortcut icon" href="{% static "portfolio/Logo.png" %}" type="image/x-icon">
    <link href="https://fonts.googleapis.com/css?family=Roboto:300,400,700&amp;subset=cyrillic-ext" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'portfolio/bootstrap-reboot.min.css' %}">
    <link rel="stylesheet" href="{% static 'portfolio/bootstrap-grid.min.css' %}">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.2/css/all.css" integrity="sha384-oS3vJWv+0UjzBfQzYUhtDYW+Pj2yciDJxpsK1OYPAYjqT085Qq/1cq5FLXAZQ7Ay" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'portfolio/style.css' %}">
</head>
  <body>

    <header>
      <nav>
        <div class="container">
            <ul class="menu">
                <li class="menu_item"><a href="{% url 'home' %}" class="menu_link">Главная</a></li>
                <li class="menu_item"><a href="#about" class="menu_link">О Храме</a></li>
                <li class="menu_item"><a href="#news" class="menu_link">Новости Храма</a></li>
                <li class="menu_item"><a href="{% url 'blog:all_blogs' %}" class="menu_link">Расписание Служб</a></li>
                <li class="menu_item"><a href="https://www.instagram.com/khram.nikity.ispovednika/" class="menu_link">Instagram</a></li>
                <li class="menu_item"><a href="#contacts" class="menu_link">Контакты</a></li>
            </ul>
        </div>
        <div class="hamburger">
            <span></span>
            <span></span>
            <span></span>
        </div>
    </nav>
    </header>


    {% block content %}{% endblock %}
    

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
    <script src="{% static 'portfolio/script.js' %}"></script>
  </body>
</html>

portfolio/templates/portfolio/home.html
{% extends "portfolio/base.html" %}

{% load static %}

{% block content %}

<section class="promo">
  <div class="container">
      <div class="row">
          <div class="col-md-12 offset-md-0 col-lg-10 offset-lg-1">
              <h1 class="promo_header">Храм Никиты Исповедника</h1>
              <h2 class="promo_subheader">Основанный в период с 1782 по 1795гг.</h2>
              <div class="promo_descr">
                Единственный уцелевший в Волгограде старинный храм (1795 года постройки).  Не действовал только три года: с 1940 по 1943 г.г. Приход многоклирный. Богослужения совершаются ежедневно. С 1990 г. проводятся реставрационные стен алтаря и верхнего яруса колокольни. Имеется воскресная школа «Святитель Феодор Епископ Едесский» и библиотека. 
                  <br><br>
                  Священники прихода посещают школу интернат №4, средние школы № 24, №57, №122, Волгоградский Государственный Университет, а также ведут душепопечительскую работу в больнице №1, №7, больнице «Каустик» и хосписе.
              </div>
              <button class="promo_btn"><a href="#about" class="menu_link">О Храме</a></button>
          </div>
      </div>
  </div>
</section>

<section class="about" id="about">
  <div class="container">
    <div class="about_title">О Храме</div>
    <div class="about_wrapper">
      <img src="{% static 'portfolio/khram2.jpg' %}" alt="" class="about_img">
      <div class="about_text"><p>Волгоградская Свято-Никитская церковь была сооружена в 18 веке на средства мецената, фаворита императрицы Никиты Бекетова. Будучи воспитанником шляхетского корпуса, Никита участвовал в спектаклях, даваемых в присутствии императрицы Елизаветы Петровны, и обратил на себя ее внимание. После выпуска из корпуса премьер-майор Бекетов был зачислен адъютантом к графу А. Г. Разумовскому, в скором времени фаворит был произведен в чин полковника и получил богатые поместья в качестве даров от императрицы. На сайте parusvlg.ru читайте подробности.В середине 18 века по приказу императрицы Екатерины II Никита Афанасьевич назначается астраханским губернатором, спустя время – сенатором и получает во владение земли возле крепости Царицына, здесь он и основал село Отрада, ставшее его имением (в настоящее время территория села относится к Волгограду). В 1782 году Бекетов создал церковь своему святому покровителю Никите-исповеднику.</p>
      <p>Для сооружения Волгоградского храма Никита Афанасьевич взял во владении завод выстроенный из кирпича и на его месте была сооружена Свято-Никитская церковь и трапезная, колокольня и купол оставались деревянными.</p>
      <p>Спустя годы церковь начала рушиться, в 1867 именитый землевладелец Царицына Валериан Попов, взялся за починку здания и пожертвовал на ремонт 120 рублей, в дополнение к 400 рублям приходских денег. В церкви сменили деревянные окна и двери, а также выстроили сторожку. В этом же году деревянную колокольню перестроили в каменную, после чего приступили строить приделы к церкви. До сегодняшнего дня сохранились голландские печи в приделах и кованые решетки на окнах.</p></div>
    </div>
  </div>
</section>

<section class="news" id="news">
  <div class="container">
    <div class="about_title">Новости Храма</div>
    <div class="news_wrapper">

      {% for project in projects %}

      {% if project.url %}
        <a href="{{ project.url }}">
          <img src="{{ project.image.url }}" class="news_img">
        </a>
      {% endif %}

      {% if project.img %}
      <img src="{{ project.image.url }}" class="news_img">
      {% endif %}
      
        <div class="news_text">
          <h2 class="news_title">{{ project.title }}</h2>
          <p class="news_descr">{{ project.description }}</p>
        </div>
      {% endfor %}
    </div>
  </div>
</section>
<footer class="footer">
  <iframe src="https://yandex.ru/map-widget/v1/?um=constructor%3Ada27727d011f79bb97d801756bfc28a611be609c593f45ee1ffc28bfb18d4477&amp;source=constructor" width="100%" height="630" frameborder="0"></iframe>

  <div class="footer__info" id="contacts">
    <address class="footer__addr">Волгоград, Абганеровская ул., 110А</address>
    <a class="footer__phone" href="tel:+78442445887">8 (8442) 44-58-87</a>
    <div class="footer__social">
        <a href="https://www.instagram.com/khram.nikity.ispovednika/" class="footer__social-item"><img src="{% static 'portfolio/instagram.svg' %}" alt="instagram"></a>
    </div>
</div>
</footer>

{% endblock %}